addSbtPlugin("ch.epfl.lamp"              % "sbt-dotty"         % "0.5.2")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"      % "0.1.16")
addSbtPlugin("org.xerial.sbt"            % "sbt-sonatype"      % "3.9.5")
addSbtPlugin("com.jsuereth"              % "sbt-pgp"           % "2.1.1")
addSbtPlugin("com.eed3si9n"              % "sbt-projectmatrix" % "0.7.0")
addSbtPlugin("org.scala-js"              % "sbt-scalajs"       % "1.5.0")
