addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"        % "0.1.20")
addSbtPlugin("org.xerial.sbt"            % "sbt-sonatype"        % "3.9.10")
addSbtPlugin("com.github.sbt"            % "sbt-pgp"             % "2.1.2")
addSbtPlugin("com.eed3si9n"              % "sbt-projectmatrix"   % "0.8.0")
addSbtPlugin("org.scala-js"              % "sbt-scalajs"         % "1.7.1")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"        % "2.4.3")
addSbtPlugin("org.scoverage"             % "sbt-scoverage"       % "1.9.0")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalajs-bundler" % "0.20.0")
