name: Scala CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: test/coverage
      run: sbt --client clean coverage test coverageReport
    - name: upload coverage
      uses: codecov/codecov-action@v1
      with:
        files: semver4s/target/jvm-2.13/scoverage-report/scoverage.xml
    - name: Check scalafmt
      run: sbt --client scalafmtCheckAll
    - name: Check scalafmt of sbt files
      run: sbt --client scalafmtSbtCheck
